import { useState } from "react";
import { trpc } from "@/providers/trpc";
import { useNavigate } from "react-router";
import {
  ArrowLeft, CheckCircle, AlertTriangle, Users, Clock,
  FileText, TrendingUp, Award, AlertCircle, CheckSquare,
  ChevronDown, ChevronUp, Share2, BarChart3,
  MessageSquare, Send, RotateCcw, PartyPopper
} from "lucide-react";

const ROLE_NAMES: Record<string, string> = {
  "team-lead": "Team Lead", "camera-operator": "Camera Operator",
  "stream-operator": "Stream Operator", "sound-engineer": "Sound Engineer",
  presentation: "Presentation", content: "Content",
  lighting: "Lighting", photography: "Photography",
};

const PHASE_LABELS: Record<string, string> = {
  arrival: "Arrival", video: "Video", presentation: "Presentation",
  streaming: "Streaming", audio: "Audio", golive: "Go Live",
  during: "During Service", post: "Post Service",
};

const PHASE_COLORS: Record<string, string> = {
  arrival: "#4A32A0", video: "#3b82f6", presentation: "#10b981",
  streaming: "#8b5cf6", audio: "#f59e0b", golive: "#f97316",
  during: "#06b6d4", post: "#2E8B57",
};

function timeAgo(date: Date | string | null | undefined): string {
  if (!date) return "just now";
  const diff = Date.now() - new Date(date).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

function formatDuration(minutes: number): string {
  if (minutes < 60) return `${minutes}m`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}

function generateReportText(report: any): string {
  const lines: string[] = [];
  lines.push(`*MediaPrep Report - ${new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}*`);
  lines.push("");
  lines.push(`Overall Completion: ${report.overallPercent}%`);
  lines.push(`Team: ${report.teamSize} members | Duration: ${formatDuration(report.durationMinutes)}`);
  lines.push(`Tasks: ${report.totalCompleted}/${report.totalTasks} completed`);
  lines.push(`Issues: ${report.totalIssues} reported (${report.resolvedIssues} resolved, ${report.openIssues} open)`);
  lines.push("");
  lines.push("*Team Performance:*");
  for (const m of report.teamStats) {
    const emoji = m.percent >= 80 ? "✅" : m.percent >= 50 ? "⚠️" : "🔴";
    lines.push(`${emoji} ${m.name} (${ROLE_NAMES[m.role] || m.role}): ${m.percent}%`);
  }
  if (report.issues.length > 0) {
    lines.push("");
    lines.push("*Issues:*");
    for (const i of report.issues) {
      const emoji = i.severity === "high" ? "🔴" : i.severity === "medium" ? "🟡" : "🔵";
      lines.push(`${emoji} ${i.description.substring(0, 60)}${i.description.length > 60 ? "..." : ""} - ${i.reporterName}`);
    }
  }
  lines.push("");
  lines.push("_Generated by MediaPrep_");
  return lines.join("\n");
}

export default function Report() {
  const navigate = useNavigate();
  const [showIssues, setShowIssues] = useState(true);
  const [showActivity, setShowActivity] = useState(true);
  const [showTeam, setShowTeam] = useState(true);
  const [shareMode, setShareMode] = useState<"none" | "copied" | "whatsapp" | "email">("none");

  const sixHoursAgo = new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString();
  const { data: report } = trpc.report.getServiceReport.useQuery({ since: sixHoursAgo });

  const handleCopy = () => {
    if (!report) return;
    navigator.clipboard?.writeText(generateReportText(report));
    setShareMode("copied");
    setTimeout(() => setShareMode("none"), 2000);
  };

  const handleWhatsApp = () => {
    if (!report) return;
    const text = encodeURIComponent(generateReportText(report));
    window.open(`https://wa.me/?text=${text}`, "_blank");
    setShareMode("whatsapp");
    setTimeout(() => setShareMode("none"), 2000);
  };

  const handleEmail = () => {
    if (!report) return;
    const subject = encodeURIComponent(`MediaPrep Report - ${new Date().toLocaleDateString()}`);
    const body = encodeURIComponent(generateReportText(report));
    window.open(`mailto:?subject=${subject}&body=${body}`, "_blank");
    setShareMode("email");
    setTimeout(() => setShareMode("none"), 2000);
  };

  // Empty state — no activity yet
  const hasNoData = !report || (report.totalCompleted === 0 && report.issues.length === 0);

  if (hasNoData) {
    return (
      <div className="min-h-screen bg-[#1A1A1A] text-[#FCFBF9] flex items-center justify-center">
        <div className="text-center px-6">
          <div className="w-20 h-20 bg-[rgba(74,50,160,0.1)] rounded-full flex items-center justify-center mx-auto mb-5">
            <PartyPopper className="w-8 h-8 text-[#4A32A0]" />
          </div>
          <h1 className="text-2xl font-bold mb-2" style={{ letterSpacing: "-0.015em" }}>
            Service Hasn't Started Yet
          </h1>
          <p className="text-[14px] text-[#797774] max-w-sm mx-auto mb-6 leading-relaxed">
            Come back here after service to see a full summary of how your team performed — completion rates, issues flagged, and who did what.
          </p>
          <button
            onClick={() => navigate("/")}
            className="h-12 px-8 bg-[#4A32A0] text-[#FCFBF9] text-[11px] font-bold uppercase tracking-wider rounded hover:bg-[#351C75] transition-colors"
            style={{ letterSpacing: "0.03em" }}
          >
            Back to Checklist
          </button>
        </div>
      </div>
    );
  }

  const topPerformer = report.teamStats.reduce((best: typeof report.teamStats[0], member: typeof report.teamStats[0]) =>
    member.percent > best.percent ? member : best, report.teamStats[0]);

  const criticalIssues = report.issues.filter((i: typeof report.issues[0]) => i.severity === "high" && !i.resolved);

  return (
    <div className="min-h-screen bg-[#1A1A1A] text-[#FCFBF9]">
      {/* Header */}
      <header className="border-b border-[rgba(252,251,249,0.08)]">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button onClick={() => navigate("/")} className="text-[#797774] hover:text-[#FCFBF9] transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div className="flex items-center gap-3">
              <FileText className="w-6 h-6 text-[#4A32A0]" />
              <div>
                <h1 className="text-xl font-bold tracking-tight" style={{ letterSpacing: "-0.015em" }}>
                  Post-Service Report
                </h1>
                <p className="text-[11px] text-[#797774] uppercase" style={{ letterSpacing: "0.03em" }}>
                  {new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}
                </p>
              </div>
            </div>
          </div>
          {/* Share buttons */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleWhatsApp}
              className="h-9 px-3 border border-[rgba(252,251,249,0.08)] text-[#797774] text-[10px] font-bold uppercase tracking-wider rounded hover:border-[#10b981] hover:text-[#10b981] transition-all flex items-center gap-1.5"
              style={{ letterSpacing: "0.03em" }}
            >
              <MessageSquare className="w-3.5 h-3.5" /> WhatsApp
            </button>
            <button
              onClick={handleEmail}
              className="h-9 px-3 border border-[rgba(252,251,249,0.08)] text-[#797774] text-[10px] font-bold uppercase tracking-wider rounded hover:border-[#3b82f6] hover:text-[#3b82f6] transition-all flex items-center gap-1.5"
              style={{ letterSpacing: "0.03em" }}
            >
              <Send className="w-3.5 h-3.5" /> Email
            </button>
            <button
              onClick={handleCopy}
              className={`h-9 px-3 border text-[10px] font-bold uppercase tracking-wider rounded transition-all flex items-center gap-1.5 ${
                shareMode === "copied"
                  ? "border-[#2E8B57] text-[#2E8B57] bg-[rgba(46,139,87,0.1)]"
                  : "border-[rgba(252,251,249,0.08)] text-[#797774] hover:border-[#FCFBF9] hover:text-[#FCFBF9]"
              }`}
              style={{ letterSpacing: "0.03em" }}
            >
              {shareMode === "copied" ? <CheckCircle className="w-3.5 h-3.5" /> : <Share2 className="w-3.5 h-3.5" />}
              {shareMode === "copied" ? "Copied" : "Copy"}
            </button>
          </div>
        </div>
      </header>

      <div className="max-w-4xl mx-auto px-6 py-6">
        {/* Hero Stats */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl p-5 text-center">
            <TrendingUp className="w-6 h-6 text-[#4A32A0] mx-auto mb-2" />
            <div className="text-3xl font-extrabold" style={{ letterSpacing: "-0.015em", color: report.overallPercent >= 80 ? "#2E8B57" : report.overallPercent >= 50 ? "#F1A208" : "#C32E2E" }}>
              {report.overallPercent}%
            </div>
            <div className="text-[11px] text-[#797774] uppercase mt-1" style={{ letterSpacing: "0.03em" }}>Completion</div>
          </div>
          <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl p-5 text-center">
            <Users className="w-6 h-6 text-[#4A32A0] mx-auto mb-2" />
            <div className="text-3xl font-extrabold" style={{ letterSpacing: "-0.015em" }}>{report.teamSize}</div>
            <div className="text-[11px] text-[#797774] uppercase mt-1" style={{ letterSpacing: "0.03em" }}>Team Members</div>
          </div>
          <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl p-5 text-center">
            <Clock className="w-6 h-6 text-[#F1A208] mx-auto mb-2" />
            <div className="text-3xl font-extrabold" style={{ letterSpacing: "-0.015em" }}>{formatDuration(report.durationMinutes)}</div>
            <div className="text-[11px] text-[#797774] uppercase mt-1" style={{ letterSpacing: "0.03em" }}>Prep Duration</div>
          </div>
          <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl p-5 text-center">
            <AlertTriangle className="w-6 h-6 text-[#C32E2E] mx-auto mb-2" />
            <div className="text-3xl font-extrabold" style={{ letterSpacing: "-0.015em", color: report.openIssues > 0 ? "#C32E2E" : "#2E8B57" }}>
              {report.openIssues}
            </div>
            <div className="text-[11px] text-[#797774] uppercase mt-1" style={{ letterSpacing: "0.03em" }}>Open Issues</div>
          </div>
        </div>

        {/* Summary Card */}
        <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl p-6 mb-8">
          <h2 className="text-[15px] font-bold mb-4 flex items-center gap-2">
            <Award className="w-4 h-4 text-[#4A32A0]" />
            Service Summary
          </h2>
          <div className="space-y-3">
            <div className="flex items-start gap-3">
              <CheckCircle className="w-4 h-4 text-[#2E8B57] mt-0.5 flex-shrink-0" />
              <p className="text-[13px]">
                <strong>{report.totalCompleted}</strong> of <strong>{report.totalTasks}</strong> tasks completed
                {report.overallPercent >= 80 && " — Excellent performance!"}
                {report.overallPercent >= 50 && report.overallPercent < 80 && " — Solid effort."}
                {report.overallPercent < 50 && " — Room for improvement."}
              </p>
            </div>
            {topPerformer && (
              <div className="flex items-start gap-3">
                <Award className="w-4 h-4 text-[#4A32A0] mt-0.5 flex-shrink-0" />
                <p className="text-[13px]">
                  <strong>Top performer:</strong> {topPerformer.name} at {topPerformer.percent}%
                </p>
              </div>
            )}
            {report.totalIssues > 0 && (
              <div className="flex items-start gap-3">
                <AlertCircle className="w-4 h-4 text-[#F1A208] mt-0.5 flex-shrink-0" />
                <p className="text-[13px]">
                  <strong>{report.totalIssues}</strong> issues — {report.resolvedIssues} resolved, {report.openIssues} open
                </p>
              </div>
            )}
            {criticalIssues.length > 0 && (
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-4 h-4 text-[#C32E2E] mt-0.5 flex-shrink-0" />
                <p className="text-[13px] text-[#C32E2E]">
                  <strong>{criticalIssues.length} critical issue(s)</strong> need attention before next service
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Phase Breakdown */}
        <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl p-6 mb-8">
          <h2 className="text-[15px] font-bold mb-5 flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-[#4A32A0]" />
            Phase Breakdown
          </h2>
          <div className="space-y-4">
            {report.phaseBreakdown.map((phase) => (
              <div key={phase.phase}>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[13px] font-medium">{PHASE_LABELS[phase.phase] || phase.phase}</span>
                  <span className="text-[11px] font-bold tabular-nums" style={{ color: phase.percent >= 80 ? "#2E8B57" : phase.percent >= 50 ? "#F1A208" : "#C32E2E" }}>
                    {phase.percent}% ({phase.completed}/{phase.total})
                  </span>
                </div>
                <div className="w-full h-[6px] bg-[rgba(252,251,249,0.06)] rounded-full overflow-hidden">
                  <div className="h-full rounded-full transition-all duration-700" style={{ width: `${phase.percent}%`, background: PHASE_COLORS[phase.phase] || "#4A32A0" }} />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Team Performance */}
        <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl overflow-hidden mb-8">
          <button onClick={() => setShowTeam(!showTeam)} className="w-full px-6 py-4 flex items-center justify-between border-b border-[rgba(252,251,249,0.04)]">
            <h2 className="text-[15px] font-bold flex items-center gap-2"><Users className="w-4 h-4 text-[#4A32A0]" />Team Performance</h2>
            {showTeam ? <ChevronUp className="w-4 h-4 text-[#797774]" /> : <ChevronDown className="w-4 h-4 text-[#797774]" />}
          </button>
          {showTeam && (
            <div className="divide-y divide-[rgba(252,251,249,0.04)]">
              {report.teamStats.map((member) => (
                <div key={member.userId} className="px-6 py-4 flex items-center gap-4">
                  <div className="w-10 h-10 bg-[#4A32A0] rounded flex items-center justify-center text-[#FCFBF9] font-bold text-sm flex-shrink-0">{(member.name || "U").charAt(0).toUpperCase()}</div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-[13px] font-semibold">{member.name}</span>
                      <span className="text-[13px] font-bold tabular-nums" style={{ color: member.percent >= 80 ? "#2E8B57" : member.percent >= 50 ? "#F1A208" : "#C32E2E" }}>{member.percent}%</span>
                    </div>
                    <div className="w-full h-[4px] bg-[rgba(252,251,249,0.06)] rounded-full overflow-hidden">
                      <div className="h-full rounded-full" style={{ width: `${member.percent}%`, background: member.percent >= 80 ? "#2E8B57" : member.percent >= 50 ? "#F1A208" : "#C32E2E" }} />
                    </div>
                    <p className="text-[11px] text-[#797774] mt-1">{ROLE_NAMES[member.role] || member.role} — {member.completed}/{member.total}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Issues */}
        {report.issues.length > 0 && (
          <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl overflow-hidden mb-8">
            <button onClick={() => setShowIssues(!showIssues)} className="w-full px-6 py-4 flex items-center justify-between border-b border-[rgba(252,251,249,0.04)]">
              <h2 className="text-[15px] font-bold flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-[#C32E2E]" />Issues ({report.issues.length})</h2>
              {showIssues ? <ChevronUp className="w-4 h-4 text-[#797774]" /> : <ChevronDown className="w-4 h-4 text-[#797774]" />}
            </button>
            {showIssues && (
              <div className="divide-y divide-[rgba(252,251,249,0.04)]">
                {report.issues.map((issue) => (
                  <div key={issue.id} className="px-6 py-4 flex gap-3">
                    <div className="w-2.5 h-2.5 rounded-full mt-1.5 flex-shrink-0" style={{ background: issue.severity === "high" ? "#C32E2E" : issue.severity === "medium" ? "#F1A208" : "#3b82f6" }} />
                    <div className="flex-1">
                      <p className="text-[13px] font-medium">{issue.description}</p>
                      <div className="flex items-center gap-3 mt-1">
                        <span className="text-[11px] text-[#797774]">By: {issue.reporterName}</span>
                        <span className={`text-[11px] font-bold uppercase px-2 py-0.5 rounded ${issue.resolved ? "bg-[rgba(46,139,87,0.15)] text-[#2E8B57]" : issue.severity === "high" ? "bg-[rgba(195,46,46,0.15)] text-[#C32E2E]" : "bg-[rgba(241,162,8,0.15)] text-[#F1A208]"}`} style={{ letterSpacing: "0.03em" }}>
                          {issue.resolved ? "Resolved" : issue.severity}
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Activity Timeline */}
        {report.recentActivity.length > 0 && (
          <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl overflow-hidden mb-8">
            <button onClick={() => setShowActivity(!showActivity)} className="w-full px-6 py-4 flex items-center justify-between border-b border-[rgba(252,251,249,0.04)]">
              <h2 className="text-[15px] font-bold flex items-center gap-2"><CheckSquare className="w-4 h-4 text-[#4A32A0]" />Activity ({report.recentActivity.length})</h2>
              {showActivity ? <ChevronUp className="w-4 h-4 text-[#797774]" /> : <ChevronDown className="w-4 h-4 text-[#797774]" />}
            </button>
            {showActivity && (
              <div className="divide-y divide-[rgba(252,251,249,0.04)] max-h-[400px] overflow-y-auto">
                {report.recentActivity.map((activity) => (
                  <div key={activity.id} className="px-6 py-3 flex items-start gap-3">
                    <CheckSquare className="w-3.5 h-3.5 text-[#2E8B57] mt-0.5 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-[12px]">
                        <span className="font-semibold">{activity.userName}</span>
                        <span className="text-[#797774]"> completed </span>
                        <span>{activity.itemText.length > 60 ? activity.itemText.substring(0, 60) + "..." : activity.itemText}</span>
                      </p>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className="text-[10px] text-[#797774]">{PHASE_LABELS[activity.itemPhase] || activity.itemPhase}</span>
                        <span className="text-[10px] text-[#797774]">{timeAgo(activity.timestamp)}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Share Section */}
        <div className="bg-black border border-[rgba(252,251,249,0.08)] rounded-xl p-6 mb-8">
          <h2 className="text-[15px] font-bold mb-4 flex items-center gap-2">
            <Share2 className="w-4 h-4 text-[#4A32A0]" />
            Share Report
          </h2>
          <div className="grid grid-cols-3 gap-3">
            <button onClick={handleWhatsApp} className="h-12 bg-[rgba(16,185,129,0.1)] border border-[rgba(16,185,129,0.2)] text-[#10b981] text-[11px] font-bold uppercase tracking-wider rounded hover:bg-[rgba(16,185,129,0.2)] transition-all flex items-center justify-center gap-2" style={{ letterSpacing: "0.03em" }}>
              <MessageSquare className="w-4 h-4" /> WhatsApp
            </button>
            <button onClick={handleEmail} className="h-12 bg-[rgba(59,130,246,0.1)] border border-[rgba(59,130,246,0.2)] text-[#3b82f6] text-[11px] font-bold uppercase tracking-wider rounded hover:bg-[rgba(59,130,246,0.2)] transition-all flex items-center justify-center gap-2" style={{ letterSpacing: "0.03em" }}>
              <Send className="w-4 h-4" /> Email
            </button>
            <button onClick={handleCopy} className={`h-12 border text-[11px] font-bold uppercase tracking-wider rounded transition-all flex items-center justify-center gap-2 ${shareMode === "copied" ? "bg-[rgba(46,139,87,0.1)] border-[rgba(46,139,87,0.3)] text-[#2E8B57]" : "bg-[rgba(252,251,249,0.03)] border-[rgba(252,251,249,0.08)] text-[#797774] hover:text-[#FCFBF9] hover:border-[rgba(252,251,249,0.2)]"}`} style={{ letterSpacing: "0.03em" }}>
              {shareMode === "copied" ? <CheckCircle className="w-4 h-4" /> : <Share2 className="w-4 h-4" />}
              {shareMode === "copied" ? "Copied" : "Copy Text"}
            </button>
          </div>
        </div>

        {/* Reset CTA */}
        <div className="text-center pb-8">
          <button
            onClick={() => { if (confirm("Reset all checklist progress for next service?")) navigate("/admin"); }}
            className="h-12 px-6 bg-[#4A32A0] text-[#FCFBF9] text-[11px] font-bold uppercase tracking-wider rounded hover:bg-[#351C75] transition-colors flex items-center gap-2 mx-auto"
            style={{ letterSpacing: "0.03em" }}
          >
            <RotateCcw className="w-4 h-4" />
            Reset for Next Service
          </button>
        </div>
      </div>
    </div>
  );
}
